spring.application.name=api-tarefas

spring.datasource.url=jdbc:postgresql://localhost:5432/api_tarefas
spring.datasource.username=postgres
spring.datasource.password=374624

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true